terraform {
 required_providers {
 aws = {
 source = "hashicorp/aws"
 version = "4.12.1"
 }
 }
}


provider "aws" {
 region = "us-east-2" 
}


resource "aws_s3_bucket" "K21_CI_CD_bucket" {
 bucket = "k21-demo-github-action-tf-medium"
 object_lock_enabled = false
 tags = {
 Environment = "Prod"
 }
}


